import type { Config } from "tailwindcss"

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: {
          primary:   "var(--bg-primary)",
          secondary: "var(--bg-secondary)",
          tertiary:  "var(--bg-tertiary)",
        },
        acc: {
          DEFAULT: "var(--acc)",
          mid:     "var(--acc-mid)",
          light:   "var(--acc-light)",
        },
        brand: {
          green:  "var(--green)",
          red:    "var(--red)",
          blue:   "var(--blue)",
          purple: "var(--purple)",
          yellow: "var(--yellow)",
        },
        text: {
          primary:   "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted:     "var(--text-muted)",
        },
        // ── Badge tokens (BADGE_SYSTEM_SPEC.md Phase 2) ──────
        badge: {
          // Product card
          discountBg:      "var(--badge-discount-bg)",
          discountText:    "var(--badge-discount-text)",
          discountBorder:  "var(--badge-discount-border)",
          hotBg:           "var(--badge-hot-bg)",
          hotText:         "var(--badge-hot-text)",
          hotBorder:       "var(--badge-hot-border)",
          saleBg:          "var(--badge-sale-bg)",
          saleText:        "var(--badge-sale-text)",
          saleBorder:      "var(--badge-sale-border)",
          newBg:           "var(--badge-new-bg)",
          newText:         "var(--badge-new-text)",
          newBorder:       "var(--badge-new-border)",
          bestsellerBg:    "var(--badge-bestseller-bg)",
          bestsellerText:  "var(--badge-bestseller-text)",
          bestsellerBorder:"var(--badge-bestseller-border)",
          comboBg:         "var(--badge-combo-bg)",
          comboText:       "var(--badge-combo-text)",
          comboBorder:     "var(--badge-combo-border)",
          // Shop card
          openBg:          "var(--badge-open-bg)",
          openText:        "var(--badge-open-text)",
          openBorder:      "var(--badge-open-border)",
          closedBg:        "var(--badge-closed-bg)",
          closedText:      "var(--badge-closed-text)",
          closedBorder:    "var(--badge-closed-border)",
          ratingBg:        "var(--badge-rating-bg)",
          ratingText:      "var(--badge-rating-text)",
          ratingBorder:    "var(--badge-rating-border)",
          distanceBg:      "var(--badge-distance-bg)",
          distanceText:    "var(--badge-distance-text)",
          distanceBorder:  "var(--badge-distance-border)",
          hasComboBg:      "var(--badge-has-combo-bg)",
          hasComboText:    "var(--badge-has-combo-text)",
          hasComboBorder:  "var(--badge-has-combo-border)",
          // Shop profile
          partnerBg:       "var(--badge-partner-bg)",
          partnerText:     "var(--badge-partner-text)",
          partnerBorder:   "var(--badge-partner-border)",
          proxyBg:         "var(--badge-proxy-bg)",
          proxyText:       "var(--badge-proxy-text)",
          proxyBorder:     "var(--badge-proxy-border)",
          // Voucher
          voucherPercentBg:    "var(--badge-voucher-percent-bg)",
          voucherPercentText:  "var(--badge-voucher-percent-text)",
          voucherPercentBorder:"var(--badge-voucher-percent-border)",
          voucherCashBg:       "var(--badge-voucher-cash-bg)",
          voucherCashText:     "var(--badge-voucher-cash-text)",
          voucherCashBorder:   "var(--badge-voucher-cash-border)",
          voucherShipBg:       "var(--badge-voucher-ship-bg)",
          voucherShipText:     "var(--badge-voucher-ship-text)",
          voucherShipBorder:   "var(--badge-voucher-ship-border)",
          voucherComboBg:      "var(--badge-voucher-combo-bg)",
          voucherComboText:    "var(--badge-voucher-combo-text)",
          voucherComboBorder:  "var(--badge-voucher-combo-border)",
          expireUrgentBg:      "var(--badge-expire-urgent-bg)",
          expireUrgentText:    "var(--badge-expire-urgent-text)",
          expireUrgentBorder:  "var(--badge-expire-urgent-border)",
          lowUsageBg:          "var(--badge-low-usage-bg)",
          lowUsageText:        "var(--badge-low-usage-text)",
          lowUsageBorder:      "var(--badge-low-usage-border)",
          // Ranking
          rank1Bg:         "var(--badge-rank-1-bg)",
          rank1Text:       "var(--badge-rank-1-text)",
          rank1Border:     "var(--badge-rank-1-border)",
          rank2Bg:         "var(--badge-rank-2-bg)",
          rank2Text:       "var(--badge-rank-2-text)",
          rank2Border:     "var(--badge-rank-2-border)",
          rank3Bg:         "var(--badge-rank-3-bg)",
          rank3Text:       "var(--badge-rank-3-text)",
          rank3Border:     "var(--badge-rank-3-border)",
          rankNBg:         "var(--badge-rank-n-bg)",
          rankNText:       "var(--badge-rank-n-text)",
          rankNBorder:     "var(--badge-rank-n-border)",
          soldCountBg:     "var(--badge-sold-count-bg)",
          soldCountText:   "var(--badge-sold-count-text)",
          soldCountBorder: "var(--badge-sold-count-border)",
          // Loyalty
          bronzeBg:        "var(--badge-bronze-bg)",
          bronzeText:      "var(--badge-bronze-text)",
          bronzeBorder:    "var(--badge-bronze-border)",
          silverBg:        "var(--badge-silver-bg)",
          silverText:      "var(--badge-silver-text)",
          silverBorder:    "var(--badge-silver-border)",
          goldBg:          "var(--badge-gold-bg)",
          goldText:        "var(--badge-gold-text)",
          goldBorder:      "var(--badge-gold-border)",
          platinumBg:      "var(--badge-platinum-bg)",
          platinumText:    "var(--badge-platinum-text)",
          platinumBorder:  "var(--badge-platinum-border)",
          // Filter chips
          filterActiveBg:      "var(--badge-filter-active-bg)",
          filterActiveText:    "var(--badge-filter-active-text)",
          filterActiveBorder:  "var(--badge-filter-active-border)",
          filterInactiveBg:    "var(--badge-filter-inactive-bg)",
          filterInactiveText:  "var(--badge-filter-inactive-text)",
          filterInactiveBorder:"var(--badge-filter-inactive-border)",
          // Spicy
          spicy1Bg:        "var(--badge-spicy-1-bg)",
          spicy1Text:      "var(--badge-spicy-1-text)",
          spicy1Border:    "var(--badge-spicy-1-border)",
          spicy2Bg:        "var(--badge-spicy-2-bg)",
          spicy2Text:      "var(--badge-spicy-2-text)",
          spicy2Border:    "var(--badge-spicy-2-border)",
          spicy3Bg:        "var(--badge-spicy-3-bg)",
          spicy3Text:      "var(--badge-spicy-3-text)",
          spicy3Border:    "var(--badge-spicy-3-border)",
          // Order status
          pendingBg:       "var(--badge-status-pending-bg)",
          pendingText:     "var(--badge-status-pending-text)",
          pendingBorder:   "var(--badge-status-pending-border)",
          goingBg:         "var(--badge-status-going-bg)",
          goingText:       "var(--badge-status-going-text)",
          goingBorder:     "var(--badge-status-going-border)",
          doneBg:          "var(--badge-status-done-bg)",
          doneText:        "var(--badge-status-done-text)",
          doneBorder:      "var(--badge-status-done-border)",
          cancelledBg:     "var(--badge-status-cancelled-bg)",
          cancelledText:   "var(--badge-status-cancelled-text)",
          cancelledBorder: "var(--badge-status-cancelled-border)",
          // Notif dot
          notifBg:         "var(--badge-notif-bg)",
          notifText:       "var(--badge-notif-text)",
          notifBgHi:       "var(--badge-notif-bg-hi)",
        },
      },
      fontFamily: {
        sans: ["Lexend", "Inter", "sans-serif"],
      },
      borderRadius: {
        "4xl": "2rem",
      },
      boxShadow: {
        acc:    "0 4px 20px rgba(255,107,0,0.4)",
        "acc-sm": "0 2px 10px rgba(255,107,0,0.3)",
      },
    },
  },
  plugins: [],
}

export default config
